- platform: mqtt
  state_topic: dummy/floorplan/sensor
  name: Floorplan

- platform: mqtt
  name: "OpenMQTTGateway"
  state_topic: "home/OpenMQTTGateway/LWT"
  payload_on: "Online"
  payload_off: "Offline"
  device_class: "connectivity"